[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.build]
cmds = [
  "cd monorepo && npm install -g pnpm",
  "cd monorepo && pnpm install",
  "cd monorepo && pnpm run build --filter apps/user"
]

[phases.start]
cmds = [
  "cd monorepo && pnpm start --filter apps/user"
]